with-expecter: True
packages:
  github.com/davidramiro/frigabun/services:
    interfaces:
      ServiceFactory:
      DnsUpdateService:
  github.com/spf13/viper:
    interfaces:
      GetBool:
      GetString: