[api]
port = 9595
# log /api/status health check endpoint requests
enableStatusLog = false
# true for pretty, false for json logging
prettyLog = true
# log level, debug/info
logLevel = "info"


[gandi]
enabled = false
baseUrl = "https://dns.api.gandi.net/api/v5"
ttl = 1800
apiKey = ""

[porkbun]
enabled = false
baseUrl = "https://api.porkbun.com/api/json/v3"
apiKey = ""
secretApiKey = ""
ttl = 1800

[cloudflare]
enabled = false
baseUrl = "https://api.cloudflare.com/client/v4"
apiKey = ""
zoneId = ""
ttl = 1800

