gandi:
  baseurl: https://dns.api.gandi.net/api/v5
  ttl: 1800
porkbun:
  baseurl: https://porkbun.com/api/json/v3
  ttl: 1800
cloudflare:
  baseurl: https://api.cloudflare.com/client/v4
  ttl: 1800
api:
  port: 9595
  hideApiKeyInLogs: true
  enableStatusLog: false
test:
  gandi:
    apiKey: YOUR-API-KEY
    domain: YOUR-DOMAIN
    subdomain: RANDOM-SUBDOMAIN
    ip: RANDOM-IP
  porkbun:
    apiKey: YOUR-API-KEY
    apiSecretKey: YOUR-SECRET-API-KEY
    domain: YOUR-DOMAIN
    subdomain: RANDOM-SUBDOMAIN
    ip: RANDOM-IP